# Generated by Django 4.1.3 on 2022-11-27 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atribut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('datatype', models.CharField(choices=[('I', 'Integer'), ('F', 'Float'), ('S', 'String')], max_length=1)),
                ('is_required', models.BooleanField(default=False)),
                ('is_price', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('validated', models.BooleanField(default=False)),
                ('nadkategorie', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.kategorie')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vyrizena', models.BooleanField(default=False)),
                ('objednavajici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dostupne_mnozstvi', models.IntegerField(blank=True, default=0, null=True)),
                ('kategorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.kategorie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_farmer', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Samosber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zacatek', models.DateTimeField(default=None)),
                ('konec', models.DateTimeField(default=None)),
                ('misto_konani', models.CharField(max_length=100)),
                ('produkty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.produkt')),
                ('uzivatel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('uzivatele', models.ManyToManyField(related_name='TEST_HERE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recenze',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnoceni', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='Produkt_Objednavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnozstvi', models.FloatField()),
                ('objednavka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.objednavka')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produkt')),
            ],
        ),
        migrations.CreateModel(
            name='AtributHodnota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intHodnota', models.IntegerField(blank=True, default=None, null=True)),
                ('floatHodnota', models.FloatField(blank=True, default=None, null=True)),
                ('strHodnota', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('atribut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atribut')),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produkt')),
            ],
        ),
        migrations.AddField(
            model_name='atribut',
            name='kategorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.kategorie'),
        ),
    ]
