# Generated by Django 4.1.3 on 2022-11-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='dostupne_mnozstvi',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
