# Generated by Django 4.1.3 on 2022-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produkt_dostupne_mnozstvi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='dostupne_mnozstvi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
