# Generated by Django 4.1.3 on 2022-11-27 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_recenze_hodnotitel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenze',
            name='hodnotitel',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
